trigger:
  - main

resources:
  - repo: self

stages:
  - stage: Build
    displayName: Build image
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: DockerCompose@0
            inputs:
              containerregistrytype: 'Azure Container Registry'
              dockerComposeFile: '**/docker-compose.yml'
              action: 'Build services'

          - task: ShellScript@2
            displayName: 'Run Docker Compose Up'
            inputs:
              scriptPath: 'scripts/run-docker-compose.sh'
