name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    env:
      SERVICE1: result
      SERVICE2: vote
      SERVICE3: worker

    steps:
      - name: Copy docker-compose file to Droplet
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: ./docker-compose.images.yml
          target: /home/${{ secrets.SSH_USERNAME }}/project

      - name: Copy healthcheck files to Droplet
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: ./healthchecks
          target: /home/${{ secrets.SSH_USERNAME }}/project

      - name: Deploy to DigitalOcean Droplet
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_KEY }}
          script: |
            source ~/.profile
            cd /home/${{ secrets.SSH_USERNAME }}/project
            docker-compose -f docker-compose.images.yml up -d
