name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      
      - name: Login to Docker registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push Docker image for vote
        uses: docker/build-push-action@v5
        with:
          context: ./vote
          file: ./vote/Dockerfile
          push: true
          tags: jpmrs1313/vote:latest

      - name: Build and push Docker image for result
        uses: docker/build-push-action@v5
        with:
          context: ./vote
          file: ./vote/Dockerfile
          push: true
          tags: jpmrs1313/result:latest
